// <auto-generated />
using System;
using BerrasBio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BerrasBio.Migrations
{
    [DbContext(typeof(BerrasBioContext))]
    [Migration("20220501144502_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BerrasBio.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("BerrasBio.Models.MovieTheater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieID")
                        .IsUnique();

                    b.ToTable("MovieTheater");
                });

            modelBuilder.Entity("BerrasBio.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("MovieID")
                        .HasColumnType("int");

                    b.Property<int?>("MovieTheaterID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieID")
                        .IsUnique()
                        .HasFilter("[MovieID] IS NOT NULL");

                    b.HasIndex("MovieTheaterID")
                        .IsUnique()
                        .HasFilter("[MovieTheaterID] IS NOT NULL");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("BerrasBio.Models.MovieTheater", b =>
                {
                    b.HasOne("BerrasBio.Models.Movie", "Movie")
                        .WithOne("Theaters")
                        .HasForeignKey("BerrasBio.Models.MovieTheater", "MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("BerrasBio.Models.Ticket", b =>
                {
                    b.HasOne("BerrasBio.Models.Movie", "Movie")
                        .WithOne("Tickets")
                        .HasForeignKey("BerrasBio.Models.Ticket", "MovieID");

                    b.HasOne("BerrasBio.Models.MovieTheater", "MovieTheater")
                        .WithOne("Ticket")
                        .HasForeignKey("BerrasBio.Models.Ticket", "MovieTheaterID");

                    b.Navigation("Movie");

                    b.Navigation("MovieTheater");
                });

            modelBuilder.Entity("BerrasBio.Models.Movie", b =>
                {
                    b.Navigation("Theaters")
                        .IsRequired();

                    b.Navigation("Tickets")
                        .IsRequired();
                });

            modelBuilder.Entity("BerrasBio.Models.MovieTheater", b =>
                {
                    b.Navigation("Ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
